server:
  port: 8087
  forward-headers-strategy: framework

spring:
  application:
    name: ms-notifications
  r2dbc:
    url: r2dbc:postgresql://notifications-db:5432/notifications_db
    username: postgres
    password: "{cipher}ba9d9ae24701a6a5d6d1f2a54f602016c299e71b97d7b627d3ecd70cf42228ed"
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://keycloak:8080/realms/eventos
          jwk-set-uri: http://keycloak:8090/realms/eventos/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.eventos.ms_notifications: DEBUG
